# Docker Compose Configuration
# visit https://docs.docker.com/compose/

version: '3.8'
services:
  app:
    container_name: chore-service
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASS: ${DATABASE_PASS}
      DATABASE_URI: ${MONGODB_URI}
    ports:
      - '3000:3000'
    depends_on:
      - database

  # start the mongodb service as container
  database:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh --port 27017  -u ${DATABASE_USER} -p ${DATABASE_PASS} --quiet
      interval: 5s
      timeout: 30s
      start_period: 0s
      retries: 30
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DATABASE_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_PASS}
