services:
  app:
    container_name: chores-service
    build:
      context: .
      dockerfile: Dockerfile.e2e
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      NODE_ENV: development
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASS: ${DATABASE_PASS}
      DATABASE_URI: ${MONGODB_URI}
    networks:
      - e2e-net
    ports:
      - '3000:3000'
    depends_on:
      - database

  database:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh --port 27017  -u ${DATABASE_USER} -p ${DATABASE_PASS} --quiet
      interval: 5s
      timeout: 30s
      start_period: 0s
      retries: 30
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DATABASE_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_PASS}
    networks:
      - e2e-net

networks:
  e2e-net:

volumes:
  pgdata:
  logs: